In [7]:
import pandas as pd 
import os
from datetime import datetime as dt

import matplotlib.pyplot as plt # always import pyplot module as plt (standard)
import numpy as np
# set seed
np.random.seed(0)
# add IPython magic command %matplotlib inline 
# to print pyplot output inline in the notebook withput calling plt.show()
%matplotlib inline

import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt

import math

In [4]:
def getTimeseriesLabel():
    # Using readlines() 
    file1 = open('./../ALT_AND_AFP_ARFF/ALT_AND_AFP_TRAIN.arff', 'r') 
    file2 = open('./../ALT_AND_AFP_ARFF/ALT_AND_AFP_TEST.arff', 'r') 
    LinesArr = []
    Lines1 = file1.readlines()
    Lines2 = file2.readlines()
    LinesArr.append(Lines1)
    LinesArr.append(Lines2)

    labelArr = []
    # Strips the newline character 
    for Lines in LinesArr:
        count = 0
        startFlag = False
        for line in Lines: 
        #     print("Line{}: {}".format(count, line.strip()))
            line = line.strip()
            if startFlag:
                line = line.split("\\n")
                for subStr in line:
                    subSubStr = subStr.split(",")
                    if len(subSubStr) == 16:
                        # Get the label of each multi-timeseries
                        label = subSubStr[15]
        #                 print(label)
                        labelArr.append(float(label))

        #         print('count: ' + str(count))
        #         print('--------')
                count += 1

            if(line=='@data'):
                startFlag = True

    print(len(labelArr))
    return labelArr

In [5]:
getTimeseriesLabel()

13787


[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0

------

In [9]:
df1 = pd.read_csv('./feature_train.txt', sep=" ", header=None)
df1.columns = ['A', 'B', 'C', 'D', 'E']
df1

A         B          C          D         E
0     1.481001  0.115571  25.952469  67.833551  0.349996
1     1.114293  0.319924  25.952501  67.833576  0.500234
2     1.625136  0.215273  25.951292  67.832679  0.314105
3     1.848055  0.397575  25.951882  67.833024  0.499791
4     1.592941  0.185638  25.952196  67.833358  0.248080
...        ...       ...        ...        ...       ...
2571  1.412551  0.271106  25.857757  67.744033  0.549310
2572  1.118292  0.195701  25.950726  67.833048  0.576320
2573  1.469533  0.138432  25.952602  67.833638  0.207704
2574  0.899566  2.401357  24.598090  66.347100  3.583684
2575  0.865066  0.328685  22.451496  64.550513  1.578959

[2576 rows x 5 columns]

In [12]:
df2 = pd.read_csv('./feature_test.txt', sep=" ", header=None)
df2.columns = ['A', 'B', 'C', 'D', 'E']
# df2
frame = [df1, df2]
df = pd.concat(frame)
df['label'] = getTimeseriesLabel()
df

13787


A         B          C          D         E  label
0      1.481001  0.115571  25.952469  67.833551  0.349996    0.0
1      1.114293  0.319924  25.952501  67.833576  0.500234    0.0
2      1.625136  0.215273  25.951292  67.832679  0.314105    0.0
3      1.848055  0.397575  25.951882  67.833024  0.499791    0.0
4      1.592941  0.185638  25.952196  67.833358  0.248080    0.0
...         ...       ...        ...        ...       ...    ...
11206  1.068035  0.252503  25.404053  67.528091  0.446448    1.0
11207  1.312140  0.111011  25.938047  67.823464  0.273982    1.0
11208  1.184979  0.212513  25.936764  67.816796  0.308108    1.0
11209  1.262717  0.265606  25.944439  67.828286  0.406295    1.0
11210  1.271772  0.315663  25.950429  67.831569  0.532457    1.0

[13787 rows x 6 columns]

In [13]:
from sklearn.linear_model import Perceptron

X = df.drop(['label'], axis=1).values
y = np.ones(df.shape[0])
y[df['label']!=0.0] = -1

# Split X and y into training and testing sets 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=4)

ppn = Perceptron(max_iter=100)

# Train the perceptron
ppn.fit(X_train, y_train)

y_pred = ppn.predict(X_test)

print("test accuracy: " + str(sum(y_test == y_pred)/len(y_pred)))

test accuracy: 0.8992023205221175


In [16]:
def outputParam(fname, coef):
    file1 = open(fname,"w")
    # \n is placed to indicate EOL (End of Line) 
    coefList = coef.flatten().tolist()
    for i in range(len(coefList)):
        aCoef = coefList[i]
        file1.write(str(aCoef))
        if i < len(coefList) - 1:
            file1.write(', ')
    file1.close() #to change file access modes

In [14]:
from sklearn.model_selection import KFold
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score

In [15]:
clf = SVC(C = 1e5, kernel = 'linear')
clf.fit(X_train, y_train)
w = clf.coef_
b = clf.intercept_
print('w = ',w)
print('b = ',b)
print('Indices of support vectors = ', clf.support_)
print('Support vectors = ', clf.support_vectors_)
print('Number of support vectors for each class = ', clf.n_support_)
print('Coefficients of the support vector in the decision function = ', np.abs(clf.dual_coef_))

w =  [[ 314.34660384  -19.34728315 2194.8478322   -65.25169754   13.74582796]]
b =  [-51834.60721348]
Indices of support vectors =  [    0    10    18 ... 11005 11022 11024]
Support vectors =  [[ 1.45785558  0.20055204 25.92745218 67.813415    0.37492453]
 [ 2.12540346  0.64661711 25.76219646 67.64014976  0.87114399]
 [ 1.70190092  0.269878   25.95245843 67.83354095  0.36747938]
 ...
 [ 2.01939934  0.53811291 25.95259635 67.83365851  0.66415997]
 [ 1.63446337  0.33092217 25.95162733 67.83288825  0.48692747]
 [ 1.71827703  0.3716737  25.95209668 67.83344443  0.46339933]]
Number of support vectors for each class =  [1017 1018]
Coefficients of the support vector in the decision function =  [[100000. 100000. 100000. ... 100000. 100000. 100000.]]


In [29]:
clf.score(X_test, y_test)

0.9053662073966643

In [19]:
# outputParam("coef.txt",w)
# outputParam("intercept.txt",b)

array([[ 9.89929784e+02, -5.40083434e+00,  1.13923507e+05,
        -8.85251155e+03,  5.59359785e+00],
       [ 9.59527562e+02, -6.87671107e+00,  1.13924032e+05,
        -8.85252185e+03,  7.88936241e+00],
       [ 8.09199956e+02, -1.01258824e+01,  1.13897442e+05,
        -8.85168616e+03,  1.05931177e+01],
       ...,
       [ 1.31658997e+03, -2.50955270e+01,  1.13922587e+05,
        -8.85248482e+03,  2.41313077e+01],
       [ 7.76758364e+02, -1.17049547e+01,  1.13608559e+05,
        -8.84966688e+03,  1.26296939e+01],
       [ 1.19783669e+03, -1.82710592e+01,  1.13922984e+05,
        -8.85249768e+03,  1.75439355e+01]])

In [43]:
# m = np.array([[ 5, 1 ,3], [ 1, 1 ,1], [ 1, 2 ,1]])
# N = np.array([1, 2, 3])
resultArr = []
multi = X*w
for row in multi:
    result = sum(row) + b
#     print(result)
    resultArr.append(result.tolist()[0])
# result[:10]

# aDf = pd.DataFrame(resultArr)
len(resultArr)

13787

In [45]:
resultDf = pd.DataFrame(resultArr)
resultDf
# resultDf.to_csv("multiplication.txt", header=None, index=False)

In [44]:
# aDf['label'] = y

0  label
0        68.733944    1.0
1       -41.279118    1.0
2       164.285063    1.0
3       334.064990    1.0
4       143.573745    1.0
...            ...    ...
2571   -527.424442   -1.0
2572    -83.085898   -1.0
2573     70.532393   -1.0
2574  -9601.113049   -1.0
2575 -22691.554810   -1.0

[2576 rows x 2 columns]

In [21]:
count = 0
for i in range(len(resultArr)):
    if y_test[i]*resultArr[i] > 0:
        count += 1 

print(count)

2497


In [23]:
2497.0/len(resultArr)

0.9053662073966643

In [17]:
clf.score(X_test, y_test)

0.6608527131782945

In [18]:
svm_classifier = SVC()

cv_accuracy = cross_val_score(svm_classifier, X, y, scoring='accuracy', cv = 5)
print(cv_accuracy)
print(cv_accuracy.mean())

[0.53100775 0.52621359 0.53203883 0.53009709 0.52427184]
0.5287258222322571


In [19]:
# a different parameter seting for RBF svm
svm_classifier = SVC(C = 100, gamma = 'auto')

cv_accuracy = cross_val_score(svm_classifier, X, y, scoring='accuracy', cv = 5)
print(cv_accuracy)
print(cv_accuracy.mean())

[0.68023256 0.66019417 0.69126214 0.6776699  0.6815534 ]
0.678182433958004


In [20]:
# A different parameter setting for SVM: linear SVM with C euqual to 5
svm_classifier = SVC(C=5, kernel = 'linear')
print(cross_val_score(svm_classifier, X, y, scoring='accuracy', cv = 5))
print(cross_val_score(svm_classifier, X, y, scoring='accuracy', cv = 5).mean())

[0.63372093 0.61165049 0.66019417 0.61747573 0.65242718]
0.6350937006096185


-----

In [ ]:
# .sort()
arr = []
for i in range(df.shape[0]):
    powerSum = 0
    alist = df.iloc[i:i+1,0:5].values.flatten().tolist()
    alist.sort()
    for j in range(5):
        powerSum += alist[j]**2
#     print(powerSum.values[0])
    arr.append(powerSum)
        
df['powerSum'] = arr
# df
df

In [ ]:
df = df.sort_values(by=['label'])
df = df.reset_index()

In [ ]:
df.tail(20)

In [ ]:
ax1 = df.loc[df['label']==1.0].powerSum.plot.hist(bins=400, figsize=(20,10))
ax1.set_xlim([5200, 5400])
ax2 = df.loc[df['label']==0.0].powerSum.plot.hist(bins=400, figsize=(20,10), color='red')
ax2.set_xlim([5200, 5400])

In [ ]:
ax1 = df[['A', 'B', 'C', 'D', 'E']].plot(figsize=(20,20))

In [ ]:
ax1 = df[['powerSum']].plot(figsize=(20,20))

In [ ]:
ax1 = df[['A', 'B']].plot(figsize=(20,20))